'use strict';

// ── Nat 1 Publishing Board Members ───────────────────────────────────────────
const CHARS = [
  // ── Voting Board ─────────────────────────────────────────────────────
  // portrait: fill in with the image URL from nat1publishing.com/about/masthead/
  // e.g. portrait: 'https://nat1publishing.com/wp-content/uploads/.../brandan.jpg'
  {
    id: 'brandan',
    name: 'Brandan Roberts',
    tagline: 'Board President',
    portrait:   null,
    shirt:      '#1a5c8a',
    pants:      '#1a1a2a',
    skin:       '#d4956a',
    hair:       '#1a1a1a',
    shoe:       '#1a1a1a',
    hasGlasses: true,
    hasBeard:   true,
    hasHat:     false,
  },
  {
    id: 'dahlia',
    name: 'Dahlia Thomas',
    tagline: 'Board Director',
    portrait:   null,
    shirt:      '#3a0a5a',
    pants:      '#1a0a2a',
    skin:       '#c8956c',
    hair:       '#1a1a1a',
    shoe:       '#0a0a0a',
    hasGlasses: false,
    hasBeard:   false,
    hasHat:     false,
  },
  {
    id: 'jason',
    name: 'Jason Willard',
    tagline: 'Creative Director',
    portrait:   null,
    shirt:      '#2a3a7a',
    pants:      '#1a2a5a',
    skin:       '#d4a070',
    hair:       '#1a0a00',
    shoe:       '#0a0a0a',
    hasGlasses: true,
    hasBeard:   true,
    hasHat:     false,
  },
  {
    id: 'jennifer',
    name: 'Jennifer Weigel',
    tagline: 'Board Director, Artist',
    portrait:   null,
    shirt:      '#3a2a5a',
    pants:      '#1a1a2a',
    skin:       '#e8c4a0',
    hair:       '#1a1a1a',
    shoe:       '#0a0a0a',
    hasGlasses: true,
    hasBeard:   false,
    hasHat:     true,
    hat:        '#4a2a5a',
  },
  {
    id: 'kathleen',
    name: 'Kathleen Locke',
    tagline: 'Board Director, Editor',
    portrait:   null,
    shirt:      '#2a1a0a',
    pants:      '#1a1a1a',
    skin:       '#c8956c',
    hair:       '#5a2a0a',
    shoe:       '#0a0a0a',
    hasGlasses: true,
    hasBeard:   false,
    hasHat:     false,
  },
  {
    id: 'michaela',
    name: 'Michaela Butler',
    tagline: 'Webmaster, Editor',
    portrait:   null,
    shirt:      '#5a0a1a',
    pants:      '#2a0a0a',
    skin:       '#c8a080',
    hair:       '#1a1a1a',
    shoe:       '#0a0a0a',
    hasGlasses: true,
    hasBeard:   false,
    hasHat:     false,
  },
  // ── Probationary Members ─────────────────────────────────────────────
  {
    id: 'cj',
    name: 'CJ the Tall Poet',
    tagline: 'Probationary Member',
    portrait:   null,
    shirt:      '#5a3010',
    pants:      '#3a2008',
    skin:       '#d4a070',
    hair:       '#1a1a1a',
    shoe:       '#2a1008',
    hasGlasses: false,
    hasBeard:   false,
    hasHat:     true,
    hat:        '#2a1808',
  },
  {
    id: 'francis',
    name: 'Francis Wiget',
    tagline: 'Probationary Member',
    portrait:   null,
    shirt:      '#3a5060',
    pants:      '#2a3848',
    skin:       '#d4b090',
    hair:       '#6a5040',
    shoe:       '#1a1a2a',
    hasGlasses: false,
    hasBeard:   true,
    hasHat:     true,
    hat:        '#2a3848',
  },
];
