'use strict';

// ── Nat 1 Publishing Board Members ───────────────────────────────────────────
// Portrait URLs use the WordPress Photon CDN. If a URL fails the card
// falls back to the pixel-art character automatically.
const CHARS = [
  // ── Voting Board ─────────────────────────────────────────────────────
  {
    id: 'brandan',
    name: 'Brandan Roberts',
    tagline: 'Board President',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2022/03/brandan.png?w=300&ssl=1',
    shirt:      '#2a62a0',
    pants:      '#1a1a2a',
    skin:       '#c8825a',
    hair:       '#2a1a10',
    shoe:       '#1a1a1a',
    hasGlasses: true,
    hasBeard:   true,
    hasHat:     true,
    hat:        '#1a1a1a',
  },
  {
    id: 'dahlia',
    name: 'Dahlia Thomas',
    tagline: 'Board Director',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2022/04/dahlia_bio-1.png?w=300&ssl=1',
    shirt:      '#2a2a3a',
    pants:      '#1a0a2a',
    skin:       '#e0b090',
    hair:       '#2a1008',
    shoe:       '#0a0a0a',
    hasGlasses: false,
    hasBeard:   false,
    hasHat:     false,
  },
  {
    id: 'jason',
    name: 'Jason Willard',
    tagline: 'Creative Director',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2022/03/JasonW.png?w=300&ssl=1',
    shirt:      '#2a3a8a',  // blue patterned blazer
    pants:      '#1a2a5a',
    skin:       '#d4a07a',
    hair:       '#7a3a18',  // auburn/brown
    shoe:       '#1a1a1a',
    hasGlasses: true,
    hasBeard:   true,
    hasHat:     false,
  },
  {
    id: 'jennifer',
    name: 'Jennifer Weigel',
    tagline: 'Board Director, Artist',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2024/03/Jenweigel_bio.png?w=300&ssl=1',
    shirt:      '#6a1a8a',
    pants:      '#4a0a6a',
    skin:       '#e8c4a0',
    hair:       '#6a4020',
    shoe:       '#2a0a3a',
    hasGlasses: true,
    hasBeard:   false,
    hasHat:     true,
    hat:        '#1a1a1a',
  },
  {
    id: 'kathleen',
    name: 'Kathleen Locke',
    tagline: 'Board Director, Editor',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2023/04/kathy_bio.png?w=300&ssl=1',
    shirt:      '#2a4a6a',
    pants:      '#1a2a3a',
    skin:       '#d4a880',
    hair:       '#6a3a18',
    shoe:       '#1a1a1a',
    hasGlasses: true,
    hasBeard:   false,
    hasHat:     false,
  },
  {
    id: 'michaela',
    name: 'Michaela Butler',
    tagline: 'Webmaster, Editor',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2024/11/michaela_2024.jpg?w=300&ssl=1',
    shirt:      '#2a0a18',
    pants:      '#1a0808',
    skin:       '#c8907a',
    hair:       '#4a1a6a',
    shoe:       '#0a0a0a',
    hasGlasses: true,
    hasBeard:   false,
    hasHat:     false,
  },
  // ── Probationary Members ─────────────────────────────────────────────
  {
    id: 'cj',
    name: 'CJ the Tall Poet',
    tagline: 'Probationary Member',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2025/02/CJPoet.png?w=300&ssl=1',
    shirt:      '#ede8e0',
    pants:      '#ede8e0',
    skin:       '#4a2810',
    hair:       '#1a0a00',
    shoe:       '#ede8e0',
    hasGlasses: false,
    hasBeard:   false,
    hasHat:     true,
    hat:        '#ede8e0',
  },
  {
    id: 'francis',
    name: 'Francis Wiget',
    tagline: 'Probationary Member',
    portrait:   'https://i0.wp.com/nat1publishing.com/wp-content/uploads/2024/11/franciswiget_bio.xcf.png?w=300&ssl=1',
    shirt:      '#5a3a18',
    pants:      '#3a2810',
    skin:       '#c8a878',
    hair:       '#4a3020',
    shoe:       '#2a1a08',
    hasGlasses: true,
    hasBeard:   true,
    hasHat:     true,
    hat:        '#1e1e1e',
  },
];
